### PR TITLE
Fix `If` node connections when regenerating materials

### LINKED ISSUE #1772: CesiumFeaturesMetadata GenerateMaterial loses connections to generated `If` nodes
Originally reported here:
https://github.com/CesiumGS/cesium-unreal/pull/1765#issuecomment-3605043691

What the user clicks `GenerateMaterial`, we recreate all connections between the generated feature ID / property value nodes and user-created nodes. However, it it doesn't correctly recreate connections to/from the generated `If` node that handles null feature IDs.

### PR DESCRIPTION
**Pull request by j9liu**
## Description

Depends on #1771, so merge that first.

Fixes #1772.

## Author checklist

- [X] I have done a full self-review of my code.
- [X] I have updated `CHANGES.md` with a short summary of my change (for user-facing changes).
- ~[ ] I have added or updated unit tests to ensure consistent code coverage as necessary.~
- ~[ ] I have updated the documentation as necessary.~

## Testing plan

1. Open `06_CesiumMetadata` in the Cesium for Unreal Samples
2. On the San Francisco Ferry Building's `UCesiumFeaturesMetadataComponent`, hit "Generate Material".
3. Observe that the `If` node remains connected to the other nodes in the graph, essentially leaving the material unchanged.

### CODE REVIEW

File: Source/CesiumRuntime/Private/GenerateMaterialUtility.h [hunk 1]
```diff
@@ -68,15 +69,36 @@ struct MaterialGenerationState {
...
+   * The details of an input connection from an autogenerated node. When nodes
+   * are regenerated, this is used to reconstruct the connection.
    */
-  TMap<FString, TMap<FString, const FExpressionInput*>> ConnectionInputRemap;
+  struct AutogeneratedInput {
+    FString nodeName;
+    FString outputName;
+  };
+  /**
+   * Describes a connection can be to a node placed by the user or to an
```
Comment (j9liu) [inline Source/CesiumRuntime/Private/GenerateMaterialUtility.h]:
```suggestion
   * Describes a connection to a node placed by the user or to an
```

**Comment by kring** [comment]
Looks good! I'll merge this after #1771 is merged.

**Comment by kring** [comment]
Thanks @j9liu!
