### PR TITLE
Fix crash with hardware raytracing and point clouds.

### LINKED ISSUE #1623: UE5.5 Crash when loading point cloud 3dtiles with hardware ray tracing enabled！
### What happened?

LoginId:01e337824964877ea56d5994defe22a5
EpicAccountId:603d626c0bd846779de449777cb70a5e

Assertion failed: Initializer.TotalPrimitiveCount > 0 [File:D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RayTracingGeometry.cpp] [Line: 203] 

UnrealEditor_RenderCore!FRayTracingGeometry::IsValid() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RayTracingGeometry.cpp:203]
UnrealEditor_Engine!FRayTracingGeometryManager::RefreshRegisteredGeometry() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Rendering\RayTracingGeometryManager.cpp:442]
UnrealEditor_Engine!FRayTracingGeometryManager::RegisterRayTracingGeometry() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Rendering\RayTracingGeometryManager.cpp:283]
UnrealEditor_RenderCore!FRayTracingGeometry::InitResource() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RayTracingGeometry.cpp:262]
UnrealEditor_Engine!`FComputeShaderUtils::AddPass<FSparseVolumeTextureUpdatePageTableCS>'::`2'::<lambda_1>::operator()() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\StaticMesh.cpp:2358]
UnrealEditor_RenderCore!`FRenderCommandPipeRegistry::StopRecording'::`2'::<lambda_1>::operator()() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:1541]
UnrealEditor_RenderCore!TGraphTask<TFunctionGraphTaskImpl<void __cdecl(void),1> >::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:634]
UnrealEditor_Core!UE::Tasks::Private::FTaskBase::TryExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Tasks\TaskPrivate.h:504]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksNamedThread() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:779]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:668]
UnrealEditor_RenderCore!RenderingThreadMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:317]
UnrealEditor_RenderCore!FRenderingThread::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:443]
UnrealEditor_Core!FRunnableThreadWin::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:159]

### Environment

Cesium for Unreal version:  2.13.3
Unreal Engine Version: 5.5
Operating System: win10

### Reproduction steps

1.
2.
3.
...

### Supporting evidence

_No response_

### PR DESCRIPTION
**Pull request by azrogers**
Fixes #1623. Currently, Cesium for Unreal will crash when trying to render a point cloud when Hardware Raytracing is enabled. You can test this out by enabling hardware raytracing and opening up the `11_CesiumPointClouds` level from the samples project. You may need to get up close and personal with the point cloud to get the crash to trigger - Unreal only seems to use raytracing for objects close to the camera. This will trigger a crash in `FRayTracingGeometry::IsValid` on the assertion `check(Initializer.TotalPrimitiveCount > 0);`. 

The cause for this crash may be fairly obvious - point clouds have no triangles, and triangles are the only primitive ray tracing seems to support (the line is literally `Initializer.TotalPrimitiveCount += Section.NumTriangles`). This means the fix is quite simple - disable ray tracing for point clouds!

### CODE REVIEW

File: Source/CesiumRuntime/Private/CesiumGltfComponent.cpp [hunk 1]
```diff
@@ -1729,10 +1729,14 @@ static void loadPrimitive(
   LODResources.bHasReversedIndices = false;
   LODResources.bHasReversedDepthOnlyIndices = false;
 
-#if ENGINE_VERSION_5_5_OR_HIGHER
+#if ENGINE_VERSION_5_5_OR_HIGHER && RHI_RAYTRACING
```
Comment (kring) [inline Source/CesiumRuntime/Private/CesiumGltfComponent.cpp:1732]: I'm curious what this `RHI_RAYTRACING` is about. I can't find any documentation for it.

**Review by kring — COMMENTED** [review]
Looks good @azrogers. Just one question...

File: Source/CesiumRuntime/Private/CesiumGltfComponent.cpp (hunk 1 above)
Comment (kring) [reply Source/CesiumRuntime/Private/CesiumGltfComponent.cpp:1732]: Ok, thanks. It makes me a little nervous because we deliver precompiled binaries to our end-users, and it's not like we're compiling one version with this flag and one without. So presumably changing this flag requires recompiling Unreal Engine itself, right? And the version Epic ships via the Launcher, for example, has it enabled (on all platforms)?

My main question is whether you added this because something broke without it? And if so, what?

Comment (azrogers) [reply Source/CesiumRuntime/Private/CesiumGltfComponent.cpp]: That's a good question. To be honest, I added it because everything in the Unreal engine code seems to use it to wrap code related to raytracing, and so it seemed like the right check to use. But I believe everything should work without it.

**Comment by kring** [comment]
Thanks @azrogers!
